### ISSUE TITLE
Different heritability of the same phenotype

### ISSUE THREAD

**Issue by Kai6662** [zhenin/HDL#14]
Hi,

When I use HDLto compute the heritability of phenotypes, I found I can get different heritability results for one phenotype (the same data set). The result of phenotype 1 with 2 is different from phenotype 1 with 3. But I used the same data. Why？ 

Best regards,
Kai

**Comment by zhenin** [comment]
Hi Kai,

This may due to
1) different SNPs in the reference panel are absent in different GWASs;
2) different `eigen.cut` was used. Please see [here](https://github.com/zhenin/HDL/wiki/Syntax-and-results-of-HDL) for more details about `eigen.cut`.R users can check `eigen.use` in the output object to find which `eigen.cut` was used.

Anyway, we do not recommend to use `HDL` to estimate heritability. More details and reasonings can be found in the [HDL paper](https://www.nature.com/articles/s41588-020-0653-y).
