### ISSUE TITLE
Access to other reference populations

### ISSUE THREAD

**Issue by samkleeman1** [zhenin/HDL#15]
Hi,

I am really keen to use this package as part of a multi-ancestry GWAS we are working on. However, I would need to know how to make the reference files in our populations of interest (AFR, EAS, CSA). Do you have any advice on this?

Kind regards,

Sam Kleeman
PhD Student, Cold Spring Harbor Laboratory, NY

**Comment by zhenin** [comment]
Hi Sam,

Thanks for your interest in HDL! We have not released instruction for making customized reference panel mainly because 

1. The reference sample for HDL has to be large enough (because the off-diagonal elements in LD matrices are important for HDL)
2. The `eigen.cut` parameter (i.e. how many leading eigens of LD should be used) needs to be tuned for different reference panels.
3. Computation is heavy and parallelization is necessary.

To avoid potential misleading results due to improper reference panels, we are still testing different scenarios. We will release an instruction if we learn more about the requirements of proper reference panels.

Best regards,
Zheng
