### ISSUE TITLE
Reference Panel links not working

### ISSUE THREAD

**Issue by HariharanJayashankar** [zhenin/HDL#17]
Hi,

I think the reference panel links aren' t working. I keep getting a 404 error. 

Sincerely,
Hari

**Comment by zhenin** [comment]
Hi Hari,

Thanks for using HDL! I just tried the link (https://www.dropbox.com/s/6zgp66s4ox6ubng/UKB_imputed_SVD_eigen99_extraction.tar.gz?dl=0), and it still works, even though Dropbox complains the file is too big to preview. Could you try again?

However, we highly recommend the use of wget command to download the file because it handles interruptions better. The commands can be found just below the dropbox link on Github. One only needs to change “/Your/path/“ in the command to the path where you want to store the file.

Best regards,
Zheng

**Comment by HariharanJayashankar** [comment]
Hm. Thats odd. I can't view that link. I tried going to it via my browser and wgetting it via command line. And I just tried wgeting on a remote server. All end up with 404s.

**Comment by HariharanJayashankar** [comment]
update: I don't get the 404 error anymore

**Comment by zhenin** [comment]
Great! Thanks for the update!
