### ISSUE TITLE
Heritability of phenotype

### ISSUE THREAD

**Issue by Kai6662** [zhenin/HDL#8]
Hey,

I used your tool to calculate my data. But the results look weird. I have 20 phenotypes and in most of them, the heritability of phenotypes is about 1 or 0.9. I think it is not possible. The GWAS results as input files were filtered on MAF > 0.01. I am not sure it is the reason or not.  

Best regards,
Kai

**Comment by zhenin** [comment]
Hi Kai,

Thanks for using HDL! Such high heritabilities are indeed weird. Could you share some HDL output as an example? Which kind of traits are you analyzing? 

Best regards,
Zheng

**Comment by Kai6662** [comment]
Hi Zheng,

I am analyzing some cell types, like neutrophils and mast cells. Here are
some examples.

[image: image.png]
[image: image.png]
[image: image.png]

Best regards,
Kai

**Comment by zhenin** [comment]
Hi Kai,

Could you send the images again on GitHub? The previous images can not be properly viewed on my side.

Best regards,
Zheng

**Comment by Kai6662** [comment]
Could you see them now?

**Comment by zhenin** [comment]
Hi Kai,

Yes, I can see them now. 

For those point estimates which are smaller than one, the standard errors are very big. Those with heritability equal to 1 with 0 standard errors are due to the estimates are constrained to be within [0,1] in the algorithm. Therefore 1 is reached in all of the jackknife results, which leads to 0 standard errors.
 
In summary, I think the extreme results may mainly because of small sample sizes, which reaches the limit of HDL. In this case, if you have individual-level data, tools like GREML may worth trying.

Best regards,
Zheng

**Comment by Kai6662** [comment]
Hi zheng,

Thanks for your help!

Best regards,
Kai
