### ISSUE TITLE
Sample size requirement

### ISSUE THREAD

**Issue by eliselucotte** [zhenin/HDL#9]
Hi !
I am using your method on GWAS results from a low sample size (about 3500 individuals), and I get the following warning:
Warning: Heritability of one trait was estimated to be 0, which may due to:
            1) The true heritability is very low;
            2) The sample size of the GWAS is too small;
            3) Many SNPs in the chosen reference panel are absent in the GWAS;
            4) There is a severe mismatch between the GWAS population and the population for computing reference
The individuals included are all of European ancestry, and the heritability of this trait is known to be high, so I guess it could be the sample size ? What is the minimum sample size required ?
Best regards,
Elise

**Comment by zhenin** [comment]
Hi Elise,

Thanks for using HDL! According to our experience, 0 heritability estimates for high heritability traits are mainly due to the above reason 3. Could you attach the full report? 

However, if the sample size is too small, heritability will indeed be underestimated because there appears to be no signal. I must apologize that It is hard to provide a rule of thumb for the minimum sample size. In general, for large heritability traits, they should require less sample to get meaningful estimates.

Best regards,
Zheng

**Comment by zhenin** [comment]
Hi Elise,

Sorry for the late response, I was busy in my dissertation and just back from a short vacation.

According to your LDSC results for GWAS2 h2 = 0.30 (se=0.15), the standard error is very high. So I guess HDL was disturbed by the relatively low sample size. Although HDL can usually provide more precise results, which can be more useful in low sample size scenarios, HDL has its limitation when the sample size is very low.

Best,
Zheng
